import pytest
from typer.testing import CliRunner

from schemaforge.cli import app
from schemaforge.generator import generate_pydantic_schemas
from schemaforge.schema import SchemaParseError, parse_schema

runner = CliRunner()


def assert_appears_before(source: str, first: str, second: str):
    assert source.index(first) < source.index(second)


def test_hello_command():
    result = runner.invoke(app, ["hello"])

    assert result.exit_code == 0
    assert "SchemaForge is alive" in result.stdout


def test_version_command():
    result = runner.invoke(app, ["version"])

    assert result.exit_code == 0
    assert "0.1.0" in result.stdout


def test_init_creates_project_files():
    with runner.isolated_filesystem():
        result = runner.invoke(app, ["init"])

        assert result.exit_code == 0
        assert "Created file: schemaforge.schema" in result.stdout
        assert "Created file: schemaforge.toml" in result.stdout
        assert "Ensured directory: app/db/generated" in result.stdout
        assert "model User" in open("schemaforge.schema", encoding="utf-8").read()
        assert open("schemaforge.toml", encoding="utf-8").read() == (
            '[schemaforge]\nschema = "schemaforge.schema"\noutput = "app/db/generated"\n'
        )


def test_init_does_not_overwrite_existing_files_without_force():
    with runner.isolated_filesystem():
        with open("schemaforge.schema", "w", encoding="utf-8") as schema_file:
            schema_file.write("existing schema")
        with open("schemaforge.toml", "w", encoding="utf-8") as config_file:
            config_file.write("existing config")

        result = runner.invoke(app, ["init"])

        assert result.exit_code == 0
        assert "Skipped existing file: schemaforge.schema" in result.stdout
        assert "Skipped existing file: schemaforge.toml" in result.stdout
        assert open("schemaforge.schema", encoding="utf-8").read() == "existing schema"
        assert open("schemaforge.toml", encoding="utf-8").read() == "existing config"


def test_init_overwrites_existing_files_with_force():
    with runner.isolated_filesystem():
        with open("schemaforge.schema", "w", encoding="utf-8") as schema_file:
            schema_file.write("existing schema")
        with open("schemaforge.toml", "w", encoding="utf-8") as config_file:
            config_file.write("existing config")

        result = runner.invoke(app, ["init", "--force"])

        assert result.exit_code == 0
        assert "Overwrote file: schemaforge.schema" in result.stdout
        assert "Overwrote file: schemaforge.toml" in result.stdout
        assert "model User" in open("schemaforge.schema", encoding="utf-8").read()
        assert "[schemaforge]" in open("schemaforge.toml", encoding="utf-8").read()


def test_parse_valid_schema():
    models = parse_schema(
        """
        model User {
          id UUID @id @default(uuid())
          email String @unique
          age Int
          bio Text?
          active Boolean
          created_at DateTime @default(now())
        }
        """
    )

    assert len(models) == 1
    user = models[0]
    assert user.name == "User"
    assert [field.name for field in user.fields] == [
        "id",
        "email",
        "age",
        "bio",
        "active",
        "created_at",
    ]
    assert user.fields[0].attributes == ("@id", "@default(uuid())")
    assert user.fields[3].optional is True


def test_parse_schema_ignores_comments_around_field_lines():
    models = parse_schema(
        """
        # user-facing account model
        model User {
          // stable primary key
          id UUID @id @default(uuid()) // generated by the application
          email String @unique # login address
          # optional profile text
          bio Text?
        }
        """
    )

    user = models[0]
    assert [field.name for field in user.fields] == ["id", "email", "bio"]
    assert user.fields[0].attributes == ("@id", "@default(uuid())")
    assert user.fields[1].attributes == ("@unique",)
    assert user.fields[2].optional is True


def test_parse_rejects_invalid_schema():
    try:
        parse_schema(
            """
            model User {
              id Float
            }
            """
        )
    except SchemaParseError as exc:
        assert "unsupported field type 'Float'" in str(exc)
    else:
        raise AssertionError("Expected invalid schema to raise SchemaParseError")


@pytest.mark.parametrize(
    ("source", "message"),
    [
        (
            """
            model User {
              id UUID
            }

            model User {
              email String
            }
            """,
            "duplicate model 'User'",
        ),
        (
            """
            model User {
              email String
              email Text
            }
            """,
            "duplicate field 'email' in model 'User'",
        ),
        (
            """
            model User {
              email String @indexed
            }
            """,
            "unsupported attribute '@indexed'",
        ),
        (
            """
            model User {
              email String @unique @unique
            }
            """,
            "duplicate attributes are not allowed",
        ),
        (
            """
            model User {
              email String
            """,
            "model 'User' is missing a closing brace",
        ),
        (
            """
            model User {
            }
            """,
            "model 'User' must contain at least one field",
        ),
    ],
)
def test_parse_rejects_invalid_important_cases(source, message):
    with pytest.raises(SchemaParseError, match=message):
        parse_schema(source)


def test_generate_pydantic_schemas_from_valid_schema():
    models = parse_schema(
        """
        model User {
          id UUID @id @default(uuid())
          email String @unique
          age Int
          bio Text?
          active Boolean
          created_at DateTime @default(now())
        }
        """
    )

    generated = generate_pydantic_schemas(models)

    assert generated == """# This file was generated by SchemaForge. Do not edit manually.

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict

class UserCreate(BaseModel):
    email: str
    age: int
    bio: str | None = None
    active: bool

class UserUpdate(BaseModel):
    id: UUID | None = None
    email: str | None = None
    age: int | None = None
    bio: str | None = None
    active: bool | None = None
    created_at: datetime | None = None

class UserRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    email: str
    age: int
    bio: str | None
    active: bool
    created_at: datetime
"""


def test_generate_pydantic_schemas_omits_unused_imports_for_primitive_schema():
    models = parse_schema(
        """
        model Post {
          title String
          views Int
          published Boolean
          body Text?
        }
        """
    )

    generated = generate_pydantic_schemas(models)

    assert "from datetime import datetime" not in generated
    assert "from uuid import UUID" not in generated
    assert "title: str" in generated
    assert "views: int" in generated
    assert "published: bool" in generated


def test_generate_pydantic_schemas_preserves_multi_model_ordering():
    models = parse_schema(
        """
        model User {
          id UUID @id @default(uuid())
          email String
        }

        model Post {
          id UUID @id @default(uuid())
          title String
          published Boolean
        }
        """
    )

    generated = generate_pydantic_schemas(models)

    assert_appears_before(
        generated,
        "class UserCreate(BaseModel):",
        "class PostCreate(BaseModel):",
    )
    assert_appears_before(
        generated,
        "class UserUpdate(BaseModel):",
        "class PostUpdate(BaseModel):",
    )
    assert_appears_before(
        generated,
        "class UserRead(BaseModel):",
        "class PostRead(BaseModel):",
    )


def test_generate_pydantic_schemas_preserves_class_block_ordering():
    models = parse_schema(
        """
        model User {
          id UUID @id @default(uuid())
          email String
        }
        """
    )

    generated = generate_pydantic_schemas(models)

    assert_appears_before(
        generated,
        "class UserCreate(BaseModel):",
        "class UserUpdate(BaseModel):",
    )
    assert_appears_before(
        generated,
        "class UserUpdate(BaseModel):",
        "class UserRead(BaseModel):",
    )


def test_generate_command_writes_schemas_file():
    with runner.isolated_filesystem():
        with open("schemaforge.schema", "w", encoding="utf-8") as schema_file:
            schema_file.write(
                """
                model User {
                  id UUID @id @default(uuid())
                  email String
                }
                """
            )

        result = runner.invoke(app, ["generate"])

        assert result.exit_code == 0
        assert "Generated Pydantic schemas: app/db/generated/schemas.py" in result.stdout
        assert "class UserCreate(BaseModel):" in open(
            "app/db/generated/schemas.py", encoding="utf-8"
        ).read()


def test_generate_command_fails_when_schema_file_is_missing():
    with runner.isolated_filesystem():
        result = runner.invoke(app, ["generate"])

        assert result.exit_code == 1
        assert "Missing schemaforge.schema. Run 'schemaforge init' first." in result.stderr


def test_generate_command_fails_when_schema_is_invalid():
    with runner.isolated_filesystem():
        with open("schemaforge.schema", "w", encoding="utf-8") as schema_file:
            schema_file.write(
                """
                model User {
                  id Float
                }
                """
            )

        result = runner.invoke(app, ["generate"])

        assert result.exit_code == 1
        assert "Invalid schema: Line 3: unsupported field type 'Float'." in result.stderr
