from __future__ import annotations

from schemaforge.schema import Model


HEADER = "# This file was generated by SchemaForge. Do not edit manually."

TYPE_MAP = {
    "String": "str",
    "Text": "str",
    "Int": "int",
    "Boolean": "bool",
    "UUID": "UUID",
    "DateTime": "datetime",
}


def generate_pydantic_schemas(models: tuple[Model, ...]) -> str:
    lines = [
        HEADER,
        "",
    ]

    imports = _required_imports(models)
    if imports:
        lines.extend(imports)
        lines.append("")

    lines.extend(
        [
            "from pydantic import BaseModel, ConfigDict",
            "",
        ]
    )

    for model in models:
        lines.extend(_render_create_model(model))
        lines.append("")
        lines.extend(_render_update_model(model))
        lines.append("")
        lines.extend(_render_read_model(model))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _required_imports(models: tuple[Model, ...]) -> list[str]:
    field_types = {field.type_name for model in models for field in model.fields}
    imports: list[str] = []

    if "DateTime" in field_types:
        imports.append("from datetime import datetime")
    if "UUID" in field_types:
        imports.append("from uuid import UUID")

    return imports


def _render_create_model(model: Model) -> list[str]:
    fields = [field for field in model.fields if not field.has_default]
    return _render_model_class(f"{model.name}Create", fields, all_optional=False)


def _render_update_model(model: Model) -> list[str]:
    return _render_model_class(f"{model.name}Update", list(model.fields), all_optional=True)


def _render_read_model(model: Model) -> list[str]:
    lines = [f"class {model.name}Read(BaseModel):", "    model_config = ConfigDict(from_attributes=True)"]
    for field in model.fields:
        lines.append(f"    {field.name}: {_field_type(field.type_name, field.optional)}")
    return lines


def _render_model_class(class_name: str, fields: list, all_optional: bool) -> list[str]:
    lines = [f"class {class_name}(BaseModel):"]
    if not fields:
        lines.append("    pass")
        return lines

    for field in fields:
        if all_optional or field.optional:
            lines.append(f"    {field.name}: {_field_type(field.type_name, True)} = None")
        else:
            lines.append(f"    {field.name}: {_field_type(field.type_name, False)}")
    return lines


def _field_type(type_name: str, optional: bool) -> str:
    python_type = TYPE_MAP[type_name]
    if optional:
        return f"{python_type} | None"
    return python_type
